name: Post-update master jobs

on:
  push:
    branches:
      - master

jobs:
  container:
    name: Container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Package Registry
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          image: server
          cache: true
          cache_registry: cache

      - name: Dockerhub
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: schemathesis/schemathesis
          cache: true
          cache_registry: schemathesis/cache
